name: Deploy to AWS Lambda
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 2.7
        run: |
          sudo apt update
          sudo apt install -y python2
          sudo ln -sf /usr/bin/python2 /usr/bin/python  # Force overwrite existing link
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
          python get-pip.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::936347005826:role/GitHubActionsLambdaDeploy
          aws-region: us-east-1
        env:
          ACTIONS_STEP_DEBUG: "true"
          AWS_DEBUG: "true" # Extra Logging
      - name: Deploy to Lambda
        run: |
          zip -r function.zip .
          aws lambda update-function-code --function-name MENTALLISTHANDLER_ALEXA --zip-file fileb://function.zip
